sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: GxKyBPO9SYPbduX49r1x0yo/wVD3bUURMW4UcxKCNsvUOJRwGMMys9oOILxJ/dit57QzNKcidBjFp/4z4m7JDf8H4PeYiA5xy5uFJDcGqjUYOk1t+xs4doa4F7imMA43WcsMCUuXaoHiXhjoAOzLk1AOuPZbKxrxmFt0LpDO7VV1OEbcyQvXbkx3pMlBbZta42/lud+WnvhC8pNeuXQ9kH+X/rr+TEG/M/QaDgEdgC296pA7WlVlk3iWBztbqAzRHMePV4AmBmT4RXRPPYCA5G7zZa3i1aUBkCNcyy36Lro+ksQh69fNBuXCfFcsjLTSveaxWxGhiEILJRiVJ5TfIO7VuZSiGw8K9Lx4ZpRfw86XZ1dZyT2AjTzooOUiQMNhl70sOvQ4BCkDr254URBLJgZLSdMV4hIymZkysuB848vo0JPu+ozCJw2DWNPJeCYLHNU2vdBP1n9RBjnq4ts9XpLuQZDwjjyfbbRhFAPPPHI+C1t6oRUXz40LIPJjSwdLIItbZ0y6XVau3QXdKloJfmRyGo3atM9S6zINbRzhMUTL911qoU5DPjF5buZjl1JwDaW1azpC46G2NUZk7y66glLT6+kQJcZaDWUYQ7tpDHN6YK24UOK1Lv4w2KAGaSu5dZOern1P8xR7MvF/4FjBhbKhxcc4J6SKjvUut7bGaWQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Right-of-Way---Complete_6249
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy